root: true
extends:
  - eslint-config-dmitmel/presets/node
env:
  browser: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  func-names: off
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
        - dynamicImport
  node/no-unsupported-features/es-builtins:
    - error
    - ignores:
        - globalThis
  node/no-unsupported-features/node-builtins:
    - error
    - ignores:
        - fs.promises

  node/no-missing-require: off
  node/no-missing-import: off
  node/no-unpublished-import: off
  node/no-unpublished-require: off
  node/no-process-exit: error
  no-undef: off
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars": error
  handle-callback-err: off

overrides:
  - files: "**/*.ts"
    extends: eslint-config-dmitmel/presets/typescript-with-type-checking-addon
    parserOptions:
      project: tsconfig.json
    rules:
      node/no-missing-import: off
      eqeqeq: off
      no-void: off
      "@typescript-eslint/naming-convention": off
